/* autogenerated. */
/* src="transcode-tblgen.rb", len=31040, checksum=17746 */
/* src="iroha.trans", len=1180, checksum=29215 */
/* src="iroha-tbl.rb", len=1057, checksum=9659 */


#include "transcode_data.h"



static const unsigned char
iroha_byte_array[905] = {
#define from_IROHA_offsets 0
0, 255,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      1,  2,  3,  4,  5,  6,  7,  8,    9, 10, 11, 12, 13, 14, 15, 16,
     17, 18, 19, 20, 21, 22, 23, 24,   25, 26, 27, 28, 29, 30, 31, 32,
     33, 34, 35, 36, 37, 38, 39, 40,   41, 42, 34, 43, 44, 45, 46, 47,
     47, 47, 47, 47, 47, 47, 47, 47,   47, 47, 47, 47, 47, 47, 47, 47,
     47, 47, 47, 47, 47, 47, 47, 47,   47, 47, 47, 47, 47, 47, 47, 47,
     47, 47, 47, 47, 47, 47, 47, 47,   47, 47, 47, 47, 47, 47, 47, 47,
     47, 47, 47, 47, 47, 47, 47, 47,   47, 47, 47, 47, 47, 47, 47, 47,
     47, 47, 47, 47, 47, 47, 47, 47,   47, 47, 47, 47, 47, 47, 47, 47,

#define to_IROHA_C2toDF_offsets 258
128, 191,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,

#define to_IROHA_E0_offsets 324
160, 191,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,

#define to_IROHA_E3_81_offsets 358
128, 191,
      1,  1,  2,  1,  3,  1,  4,  1,    5,  1,  6,  7,  1,  8,  1,  9,
      1, 10,  1, 11,  1, 12,  1, 13,    1, 14,  1, 15,  1, 16,  1, 17,
      1, 18,  1,  1, 19,  1, 20,  1,   21,  1, 22, 23, 24, 25, 26, 27,
      1,  1, 28,  1,  1, 29,  1,  1,   30,  1,  1, 31,  1,  1, 32, 33,

#define to_IROHA_E3_82_offsets 424
128, 191,
      1,  2,  3,  4,  5,  4,  6,  4,    7,  8,  9, 10, 11, 12,  4, 13,
     14,  4, 15,  4,  4,  4,  4,  4,    4,  4,  4,  4,  4,  4,  4,  4,
      4,  4,  4,  4,  4,  4,  4,  4,    4,  4,  4,  4,  4,  4,  4,  4,
      4,  4,  4,  4,  4,  4,  4,  4,    4,  4,  4,  4,  4,  4,  4,  4,

#define to_IROHA_E3_offsets 490
128, 191,
      1,  2,  3,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,

#define to_IROHA_ED_offsets 556
128, 159,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,

#define to_IROHA_F0_offsets 590
144, 191,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,

#define to_IROHA_F4_offsets 640
128, 143,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,

#define to_IROHA_offsets 658
0, 244,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,    0,  0,  0,  0,  0,  0,  0,  0,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  1,  1,  1,  1,  1,  1,    1,  1,  1,  1,  1,  1,  1,  1,
      1,  1,  2,  2,  2,  2,  2,  2,    2,  2,  2,  2,  2,  2,  2,  2,
      2,  2,  2,  2,  2,  2,  2,  2,    2,  2,  2,  2,  2,  2,  2,  2,
      3,  4,  4,  5,  4,  4,  4,  4,    4,  4,  4,  4,  4,  6,  4,  4,
      7,  8,  8,  8,  9,

};
static const unsigned int
iroha_word_array[142] = {
#define from_IROHA_infos WORDINDEX2INFO(0)
                  NOMAP, o3(0xE3,0x81,0x84),
     o3(0xE3,0x82,0x8D), o3(0xE3,0x81,0xAF),
     o3(0xE3,0x81,0xAB), o3(0xE3,0x81,0xBB),
     o3(0xE3,0x81,0xB8), o3(0xE3,0x81,0xA8),
     o3(0xE3,0x81,0xA1), o3(0xE3,0x82,0x8A),
     o3(0xE3,0x81,0xAC), o3(0xE3,0x82,0x8B),
     o3(0xE3,0x82,0x92), o3(0xE3,0x82,0x8F),
     o3(0xE3,0x81,0x8B), o3(0xE3,0x82,0x88),
     o3(0xE3,0x81,0x9F), o3(0xE3,0x82,0x8C),
     o3(0xE3,0x81,0x9D), o3(0xE3,0x81,0xA4),
     o3(0xE3,0x81,0xAD), o3(0xE3,0x81,0xAA),
     o3(0xE3,0x82,0x89), o3(0xE3,0x82,0x80),
     o3(0xE3,0x81,0x86), o3(0xE3,0x82,0x90),
     o3(0xE3,0x81,0xAE), o3(0xE3,0x81,0x8A),
     o3(0xE3,0x81,0x8F), o3(0xE3,0x82,0x84),
     o3(0xE3,0x81,0xBE), o3(0xE3,0x81,0x91),
     o3(0xE3,0x81,0xB5), o3(0xE3,0x81,0x93),
     o3(0xE3,0x81,0x88), o3(0xE3,0x81,0xA6),
     o3(0xE3,0x81,0x82), o3(0xE3,0x81,0x95),
     o3(0xE3,0x81,0x8D), o3(0xE3,0x82,0x86),
     o3(0xE3,0x82,0x81), o3(0xE3,0x81,0xBF),
     o3(0xE3,0x81,0x97), o3(0xE3,0x81,0xB2),
     o3(0xE3,0x82,0x82), o3(0xE3,0x81,0x9B),
     o3(0xE3,0x81,0x99),              UNDEF,

#define from_IROHA WORDINDEX2INFO(48)
    from_IROHA_offsets,
    from_IROHA_infos,

#define to_IROHA_C2toDF_infos WORDINDEX2INFO(50)
     INVALID,   UNDEF,

#define to_IROHA_C2toDF WORDINDEX2INFO(52)
    to_IROHA_C2toDF_offsets,
    to_IROHA_C2toDF_infos,

#define to_IROHA_E0_infos WORDINDEX2INFO(54)
             INVALID, to_IROHA_C2toDF,

#define to_IROHA_E0 WORDINDEX2INFO(56)
    to_IROHA_E0_offsets,
    to_IROHA_E0_infos,

#define to_IROHA_E1toE2 WORDINDEX2INFO(58)
    to_IROHA_C2toDF_offsets,
    to_IROHA_E0_infos,

#define to_IROHA_E3_81_infos WORDINDEX2INFO(60)
      INVALID,    UNDEF, o1(0xA3), o1(0x80),
     o1(0x97), o1(0xA1), o1(0x9A), o1(0x8D),
     o1(0xA5), o1(0x9B), o1(0x9E), o1(0xA0),
     o1(0xA4), o1(0xA9), o1(0xAE), o1(0xAD),
     o1(0x91), o1(0x8F), o1(0x87), o1(0x92),
     o1(0xA2), o1(0x86), o1(0x94), o1(0x83),
     o1(0x89), o1(0x93), o1(0x99), o1(0x82),
     o1(0xAB), o1(0x9F), o1(0x85), o1(0x84),
     o1(0x9D), o1(0xA8),

#define to_IROHA_E3_81 WORDINDEX2INFO(94)
    to_IROHA_E3_81_offsets,
    to_IROHA_E3_81_infos,

#define to_IROHA_E3_82_infos WORDINDEX2INFO(96)
      INVALID, o1(0x96), o1(0xA7), o1(0xAC),
        UNDEF, o1(0x9C), o1(0xA6), o1(0x8E),
     o1(0x95), o1(0x88), o1(0x8A), o1(0x90),
     o1(0x81), o1(0x8C), o1(0x98), o1(0x8B),

#define to_IROHA_E3_82 WORDINDEX2INFO(112)
    to_IROHA_E3_82_offsets,
    to_IROHA_E3_82_infos,

#define to_IROHA_E3_infos WORDINDEX2INFO(114)
             INVALID, to_IROHA_C2toDF,  to_IROHA_E3_81,  to_IROHA_E3_82,

#define to_IROHA_E3 WORDINDEX2INFO(118)
    to_IROHA_E3_offsets,
    to_IROHA_E3_infos,

#define to_IROHA_ED WORDINDEX2INFO(120)
    to_IROHA_ED_offsets,
    to_IROHA_E0_infos,

#define to_IROHA_F0_infos WORDINDEX2INFO(122)
             INVALID, to_IROHA_E1toE2,

#define to_IROHA_F0 WORDINDEX2INFO(124)
    to_IROHA_F0_offsets,
    to_IROHA_F0_infos,

#define to_IROHA_F1toF3 WORDINDEX2INFO(126)
    to_IROHA_C2toDF_offsets,
    to_IROHA_F0_infos,

#define to_IROHA_F4 WORDINDEX2INFO(128)
    to_IROHA_F4_offsets,
    to_IROHA_F0_infos,

#define to_IROHA_infos WORDINDEX2INFO(130)
               NOMAP,         INVALID, to_IROHA_C2toDF,     to_IROHA_E0,
     to_IROHA_E1toE2,     to_IROHA_E3,     to_IROHA_ED,     to_IROHA_F0,
     to_IROHA_F1toF3,     to_IROHA_F4,

#define to_IROHA WORDINDEX2INFO(140)
    to_IROHA_offsets,
    to_IROHA_infos,

};
#define TRANSCODE_TABLE_INFO iroha_byte_array, 905, iroha_word_array, 142, ((int)sizeof(unsigned int))
static const rb_transcoder
rb_from_IROHA = {
    "IROHA", "UTF-8", from_IROHA,
    TRANSCODE_TABLE_INFO,
    1, /* input_unit_length */
    1, /* max_input */
    1, /* max_output */
    asciicompat_converter, /* asciicompat_type */
    0, 0, 0, /* state_size, state_init, state_fini */
    0, 0, 0, 0,
    0, 0, 0
};
static const rb_transcoder
rb_to_IROHA = {
    "UTF-8", "IROHA", to_IROHA,
    TRANSCODE_TABLE_INFO,
    1, /* input_unit_length */
    4, /* max_input */
    1, /* max_output */
    asciicompat_converter, /* asciicompat_type */
    0, 0, 0, /* state_size, state_init, state_fini */
    0, 0, 0, 0,
    0, 0, 0
};


TRANS_INIT(single_byte)
{
    rb_register_transcoder(&rb_from_IROHA);
    rb_register_transcoder(&rb_to_IROHA);

}


